apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-capstone
  namespace: capstone
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /easyclaim
        backend:
          serviceName: easyclaim-frontend-service
          servicePort: 8080
